### ISSUE TITLE
Have API Contract and Request Validation with proper error handling

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-golang#12]
One important aspect of any system is that it should have a well defined and limited universe of inputs that the system will take as input. If the user sends something outside of the universe, system should throw back an appropriate error message. 

We should also have a well defined API contract, and some automated validation while parsing requests that throw appropriate HTTP 400 error.

For example, for CreateQueue API, we should define something like

```
type CreateQueueRequest struct {
    QueueName string `minLength:"4" maxLength:"16"`
}

type CreateQueueResponse model.Queue
```

If an invalid JSON body is received, we should return a 400 Bad Request and the body should indicate to the client the error, `expected , at line 4`. Or if the queueName was supposed to be string but it was not present, or an integer value was passed, that should be pointed out to the user.

**Comment by daltonfury42** [comment]
This seems to be one option: https://github.com/go-swagger/go-swagger

**Comment by daltonfury42** [comment]
As pointed out by @aneeshsharma offline, let's de-prioritise OpenAPI schema definition etc, as our requirements are not complex enough. Proposal:

1. For any field level validations etc, we would do it manually in code as and when we see a need to.
2. We will define our own request and response structures as golang types manually.

For (2), move files currently present in `internal/models` folder into `internal/models/db` as they are our database data models.

Then create new files, `internal/models/api.go` with content:
```
package api

type Queue struct { ...everything as we have in mongo... }

type CreateQueueRequest struct {
    QueueName string `minLength:"4" maxLength:"16"`
}

type CreateQueueResponse Queue
```


Then we should parse request body from CreateQueueRequest, parse output to CreateQueueResponse etc.

@aneeshsharma @maaverik thoughts?

**Comment by daltonfury42** [comment]
Thought of having a separate model for queue for external API vs what's in DB, so that it will allow us to evolve these two independently. 

For example, we might anytime have a field in the external API that's computed via code after fetching data from the DB, thus the field being present in the API model but not in DB model.

**Comment by aneeshsharma** [comment]
So, we can implement a Method for `CreateQueueRequest` to validate the data.
Now, we can either use a middleware to do the validation or do it inside the handler.

**Comment by maaverik** [comment]
Using a middleware would be cleaner and would allow more obvious reuse. Since go-chi is used, integrating middleware wouldn't be too hard either.

**Comment by aneeshsharma** [comment]
I was looking into a good way to go about validation, and came across these 2 packages
- https://github.com/go-playground/validator
- https://github.com/thedevsaddam/govalidator

But I think these too are not really required. Using any packages I feel would actually make the code more complex than simply implementing a validation function ourselves. 

This what I have in mind. We can have an interface `Validator` which can be called by the middleware.

```Go
type Validator interface {
    Validate() ValidationError
}
```
`ValidationError` could have a message along with a list of fields which were invalid

```Go
type ValidationError struct {
    message string
    fields []string
}
```

And we can then implement the `Validate` method for `CreateQueueRequest`

```Go
func (req CreateQueueRequest) Validate() ValidationError {
    ...
}
```

 Let me know what you think. If we can have a basic structure I can start on the implementation.

**Comment by maaverik** [comment]
This is a good start. The validation packages are interesting and would reduce code for us, but we don't have many endpoints, and I don't see the number increasing in the near future, so let's stick with manual functions for validation for now. It's going to be quicker than figuring out how to use the packages properly, and migrating to a package later on shouldn't be too hard once the rules are clearly defined anyway.

**Comment by daltonfury42** [comment]
+1 

I am fully in for @aneeshsharma 's approach. 🚀
