### ISSUE TITLE
Token Implementation

### ISSUE THREAD

**Issue by aneeshsharma** [SimplQ/simplQ-golang#17]
For implementing token functions in `QueueStore`
- `Token` can have a field `QueueId` which points to the queue that this token belongs to
- `Queue` would not have any reference to the tokens but when `ReadQueue` is called, we can query Mongo for all the tokens that belong to `QueueId` and have `IsDeleted == false` and add it to the result before returning the `Queue` model

So,
- `AddTokenToQueue` just needs to create a new token in `tokens` collection and add the `QueueId`
- `ReadToken` is a direct read
- `RemoveToken` will simply set the `IsDeleted` value to true

What do you think about this method? @daltonfury42 @maaverik

**Comment by aneeshsharma** [comment]
To decide the order of the tokens, we can sort by `CreationTime`

**Comment by maaverik** [comment]
This looks good to me. One thing to take care of is concurrent token creation, i.e. two people creating a token in a queue at the same time. `CreateToken` should take care of that scenario, or it could lead to two users getting the same position in the queue and other problems. 

I think this was solved in the current version using a constraint in Postgres. I don't remember if it was a unique constraint on position in queue or not, @daltonfury42  do you know?. If there is a similar constraint in Mongo, we can use that, else we might want to use some Go constructs to handle this case (like pushing all creation requests to a single channel).

**Comment by daltonfury42** [comment]
@aneeshsharma this looks good to me too.

In our java backend, the token number was assigned in three steps:
1. Query DB: Get highest token number in the queue
2. Java: newToken.tokenNumber = highest token number + 1
3. Query DB:  Save new token.

In this case when serving two concurrent requests to add new token, both the tokens could get the same token number. The fix at the time was to put both the queries into a single DB transaction and make it's isolation level SERIAL.

In your case you would also have to take care of this, either using some Mongo level tx isolation support, or if that becomes tricky, ~~you can use a mutex or something similar offered by golang.~~ using go channels might be a cool way of getting around this.

**Comment by aneeshsharma** [comment]
That is a good solution. But do we need that sort of a precision?
The timestamp will have the precision of milliseconds. So, if 2 people were to queue at the exact same time down to milliseconds, I don't think that would be a big issue if their order was either way.
We can use `_id` as the second sorting parameter to make sure the order is the same every time even when the timestamps are equal.

I think since this would require just a single operation to insert the tokens, it should be more efficient.

**Comment by maaverik** [comment]
This seems like a smart solution. I know very little about mongo internals, but at a high level, this is viable and handling this in the DB layer is probably more efficient than handling at the application layer anyway.

**Comment by daltonfury42** [comment]
> I think since this would require just a single operation to insert the tokens, it should be more efficient.

How would you set the token number of the new token?

**Comment by aneeshsharma** [comment]
We can assign token numbers when `ReadQueue` sorts the token inside the queue.

One thing to clarify, would the token number always remain the same even if any token in between is deleted?
If so, we will have to query the database for all the tokens including deleted ones.

> @aneeshsharma this looks good to me too.
> 
> In our java backend, the token number was assigned in three steps:
> 
>     1. Query DB: Get highest token number in the queue
> 
>     2. Java: newToken.tokenNumber = highest token number + 1
> 
>     3. Query DB:  Save new token.
> 
> 
> In this case when serving two concurrent requests to add new token, both the tokens could get the same token number. The fix at the time was to put both the queries into a single DB transaction and make it's isolation level SERIAL.
> 
> In your case you would also have to take care of this, either using some Mongo level tx isolation support, or if that becomes tricky, ~you can use a mutex or something similar offered by golang.~ using go channels might be a cool way of getting around this.

If the token number is essential then we may have to instead use this method. Because `ReadToken` will also get more complex if we try to derive token numbers in application layer only.

**Comment by aneeshsharma** [comment]
It might be possible to use mongo aggregate pipeline to assign token number as `highest_token + 1` when we insert. But I'll have to look into that as I haven't used it so extensively before. If it is possible to do that, then it will be more efficient than doing it in the application.

**Comment by daltonfury42** [comment]
> One thing to clarify, would the token number always remain the same even if any token in between is deleted?

Yes.

> If the token number is essential then we may have to instead use this method. Because ReadToken will also get more complex if we try to derive token numbers in application layer only.

True. Also this logic might get duplicated in ReadQueue where we would want to return all tokens in the queue.

**Comment by aneeshsharma** [comment]
I feel using a Mutex might be better.
We can have a hashmap of mutex so that only one thread will insert into a queue at a time (each queue with a mutex). I am not sure if this is efficient enough.

Using a single go channel, the implementation would be simpler but then all add token operations will be bottle necked by the single thread. Also, I am not sure on how to wait for the operation to complete before sending the http response.

**Comment by daltonfury42** [comment]
Yes, let's just have one global lock, no need of locking per queue.
